<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="1"
            failures="0"
            tests="1">

  <testsuite name="CURA.userCanLogin"
    errors="1" failures="0" hostname="" id="" package="CURA" skipped="0"
    tests="1" time="0.009000" timestamp="Wed, 11 Apr 2018 13:00:22 GMT">
  
    <testcase name="CURA Test : User Can Login" classname="CURA.userCanLogin" time="0.009000" assertions="0">
    </testcase>
  

  
    <system-err>
        Error while running [CURA / User Can Login / CURA Test : User Can Login]:

  ReferenceError: myHomePage is not defined
    at Object.CURA Test : User Can Login (C:\Users\apd2\Documents\GitHub\automation_testing_101\Nightwatch\tests\CURA\userCanLogin.js:4:27)
    at Module.call (C:\Users\apd2\Documents\GitHub\automation_testing_101\Nightwatch\node_modules\nightwatch\lib\runner\module.js:62:34)
    at C:\Users\apd2\Documents\GitHub\automation_testing_101\Nightwatch\node_modules\nightwatch\lib\runner\testcase.js:70:29
    at _fulfilled (C:\Users\apd2\Documents\GitHub\automation_testing_101\Nightwatch\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Users\apd2\Documents\GitHub\automation_testing_101\Nightwatch\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Users\apd2\Documents\GitHub\automation_testing_101\Nightwatch\node_modules\q\q.js:796:13)
    at C:\Users\apd2\Documents\GitHub\automation_testing_101\Nightwatch\node_modules\q\q.js:556:49
    at runSingle (C:\Users\apd2\Documents\GitHub\automation_testing_101\Nightwatch\node_modules\q\q.js:137:13)
    at flush (C:\Users\apd2\Documents\GitHub\automation_testing_101\Nightwatch\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    </system-err>
  

  
  </testsuite>
</testsuites>
